import { expect, test } from "@playwright/test";
import { createCollector } from "./account";
import { navigate, skipWelcomeTour } from "./navigation";

test("import decks, compare editions and export only missing copies without adding holdings", async ({ browser, request }) => {
  const account = await createCollector(request);
  const printings = (await (await request.get(account.baseURL + "/api/v1/catalog/search?q=Island&exact_name=true&language=en")).json()).items;
  const first = printings[0], alternate = printings.find((item: any) => item.id !== first.id);
  const mountain = (await (await request.get(account.baseURL + "/api/v1/catalog/search?q=Mountain&exact_name=true&language=en")).json()).items[0];
  expect(first).toBeTruthy(); expect(alternate).toBeTruthy();
  const context = await browser.newContext({ baseURL: account.baseURL, viewport: { width: 390, height: 844 }, isMobile: true, hasTouch: true });
  try {
    const page = await context.newPage();
    const errors: string[] = []; page.on("pageerror", (error) => errors.push(error.message));
    await page.goto("/"); await page.getByRole("link", { name: "Sign in", exact: true }).click();
    await page.locator("#username").fill(account.username); await page.locator("#password").fill(account.password); await page.locator("#kc-login").click();
    await skipWelcomeTour(page);
    await navigate(page, "Import / export");
    await page.getByTestId("csv-input").setInputFiles({ name: "deck-owned-fixture.csv", mimeType: "text/csv", buffer: Buffer.from(`Scryfall ID,Quantity,Location\n${first.id},2,Red binder\n`) });
    await expect(page.getByRole("heading", { name: "Ready to review", exact: true })).toBeVisible({ timeout: 30000 });
    await page.getByLabel("These are cards I own. Add the reviewed quantities to my collection.").check();
    await page.getByRole("button", { name: "Add 2 copies", exact: true }).click();
    await expect(page.getByRole("heading", { name: "Import complete", exact: true })).toBeVisible({ timeout: 30000 });
    await navigate(page, "Decks");
    await page.getByRole("button", { name: "Import deck list", exact: true }).click();
    await page.getByRole("textbox", { name: "Import deck name", exact: true }).fill("Imported plan");
    await page.getByRole("textbox", { name: "Paste deck list", exact: true }).fill(`Commander\n1 Island (${first.set_code}) ${first.collector_number}\nMainboard\n3 Island (${alternate.set_code}) ${alternate.collector_number}\nSideboard\n1 Island\n1 This is a deliberately unknown fixture card\n`);
    await page.getByRole("button", { name: "Preview deck list", exact: true }).click();
    await expect(page.getByRole("button", { name: "Import deck", exact: true })).toBeDisabled();
    const unresolved = page.locator(".deck-import-rows > li").filter({ hasText: "This is a deliberately unknown fixture card" });
    await unresolved.getByRole("button", { name: "Exclude row", exact: true }).click();
    await page.getByRole("button", { name: "Import deck", exact: true }).click();
    await expect(page.getByRole("heading", { name: "Imported plan", exact: true })).toBeVisible();
    await expect(page.getByText("Deck imported. You own 2 of 5 copies; 3 still needed.", { exact: true })).toBeVisible();
    await page.locator(".deck-shopping > summary").click();
    await expect(page.getByRole("textbox", { name: "Missing cards to copy", exact: true })).toHaveValue("3 Island");
    await expect(page.locator(".deck-cards .card-location").filter({ hasText: "Red binder (2)" })).toHaveCount(3);
    await page.getByRole("checkbox", { name: "Show only missing cards", exact: true }).check();
    await expect(page.locator(".deck-cards > li")).toHaveCount(2);
    const saved = (await (await context.request.get("/api/v1/decks")).json()).items[0];
    const matched = await (await context.request.get(`/api/v1/decks/${saved.id}`)).json();
    expect(matched.cards.every((card: any) => card.printing.id === first.id)).toBe(true);
    await expect(page.getByRole("button", { name: "Gallery", exact: true })).toHaveAttribute("aria-pressed", "true");
    const ck = await context.request.get(`/api/v1/decks/${saved.id}/buy-list?format=cardkingdom`);
    expect(await ck.text()).toBe("3 Island\n");
    await page.getByRole("button", { name: "Edit deck", exact: true }).click();
    await page.getByRole("textbox", { name: "Deck notes", exact: true }).fill("Bring blue sleeves");
    await page.getByRole("combobox", { name: "Compare with my collection", exact: true }).selectOption("exact");
    await expect(page.getByRole("link", { name: "Download buy list", exact: true })).toHaveCount(0);
    await page.getByRole("button", { name: "Save deck", exact: true }).click();
    await expect(page.getByText("Deck saved.", { exact: true })).toBeVisible();
    await page.locator(".deck-shopping > summary").click();
    await page.getByRole("combobox", { name: "Buy list format", exact: true }).selectOption("manapool");
    const data = await (await context.request.get(`/api/v1/decks/${saved.id}`)).json();
    expect(data.missing_copies).toBeGreaterThanOrEqual(3);
    const mp = await (await context.request.get(`/api/v1/decks/${saved.id}/buy-list?format=manapool`)).text();
    expect(mp).toContain(`3 Island (${first.set_code.toUpperCase()}) ${first.collector_number}`);
    expect((await (await context.request.get("/api/v1/collection")).json()).copies).toBe(2);
    expect((await (await context.request.get("/api/auth/session")).json()).scan_cards_used).toBe(0);
    await page.getByRole("region", { name: "Missing cards buy list", exact: true }).screenshot({ path: `../../artifacts/deck-buy-lists/buy-list-${browser.browserType().name()}.png` });
    if (first.image_url) expect((await context.request.get(first.image_url)).status()).toBe(200);
    await page.getByRole("button", { name: "Done editing", exact: true }).first().click();
    await page.getByRole("button", { name: "Import deck list", exact: true }).click();
    await expect(page.getByRole("heading", { name: "Import into Imported plan", exact: true })).toBeVisible();
    await page.getByRole("textbox", { name: "Paste deck list", exact: true }).fill(`Mainboard\n2 Island (${first.set_code}) ${first.collector_number}\nSideboard\n1 Island (${first.set_code}) ${first.collector_number}`);
    await page.getByRole("button", { name: "Preview deck list", exact: true }).click();
    await expect(page.locator(".deck-import-impact")).toContainText("5 → 3 cards");
    await page.getByRole("button", { name: "Replace deck list", exact: true }).click();
    await expect(page.getByRole("region", { name: "Deck overview", exact: true })).toBeVisible();
    let updated = await (await context.request.get(`/api/v1/decks/${saved.id}`)).json();
    expect(updated).toMatchObject({ id: saved.id, copies: 3, name: "Imported plan", notes: "Bring blue sleeves", match_mode: "any" });
    expect(updated.cards.some((card: any) => card.section === "commander")).toBe(false);
    await page.getByRole("button", { name: "Import deck list", exact: true }).click();
    await page.getByRole("radio", { name: /^Add to current list/ }).check();
    await page.getByLabel("Deck list file", { exact: true }).setInputFiles({ name: "additions.csv", mimeType: "text/csv", buffer: Buffer.from(`Name,Quantity,Scryfall ID,Section\nIsland,1,${first.id},main\nIsland,1,${first.id},main\n`) });
    await page.getByRole("button", { name: "Preview deck list", exact: true }).click();
    await expect(page.locator(".deck-import-impact")).toContainText("3 → 5 cards");
    await page.getByRole("button", { name: "Add cards to deck", exact: true }).click();
    await expect(page.getByRole("region", { name: "Deck overview", exact: true })).toBeVisible();
    updated = await (await context.request.get(`/api/v1/decks/${saved.id}`)).json();
    expect(updated.cards.find((card: any) => card.section === "main").quantity).toBe(4);
    expect(updated.notes).toBe("Bring blue sleeves");
    expect((await (await context.request.get("/api/v1/decks")).json()).items).toHaveLength(1);
    expect((await (await context.request.get("/api/v1/collection")).json()).copies).toBe(2);
    await page.getByRole("button", { name: "Close deck", exact: true }).click();
    const row = page.getByRole("button", { name: /Imported plan/ });
    await expect(row).toContainText("5 cards");
    await expect(row.locator("img").first()).toHaveJSProperty("complete", true);
    expect(await row.locator("img").first().evaluate((image) => (image as HTMLImageElement).naturalWidth)).toBeGreaterThan(0);
    // CSV deck import uses the same preview and preserves requested sections.
    await page.getByRole("button", { name: "Import deck list", exact: true }).click();
    await page.getByLabel("Deck list file", { exact: true }).setInputFiles({ name: "CSV plan.csv", mimeType: "text/csv", buffer: Buffer.from(`Name,Quantity,Scryfall ID,Section\nIsland,4,${alternate.id},main\nIsland,1,${alternate.id},sideboard\nMountain,1,${mountain.id},main\n`) });
    await page.getByRole("button", { name: "Preview deck list", exact: true }).click();
    await page.getByRole("button", { name: "Import deck", exact: true }).click();
    await expect(page.getByRole("heading", { name: "CSV plan", exact: true })).toBeVisible();
    await page.locator(".deck-shopping > summary").click();
    await expect(page.getByRole("textbox", { name: "Missing cards to copy", exact: true })).toHaveValue("3 Island\n1 Mountain");
    await page.reload(); await navigate(page, "Decks");
    await page.getByRole("button", { name: /CSV plan/ }).click();
    await page.locator(".deck-shopping > summary").click();
    await expect(page.getByRole("textbox", { name: "Missing cards to copy", exact: true })).toHaveValue("3 Island\n1 Mountain");
    await page.getByRole("button", { name: "Preview Mountain · Mainboard", exact: true }).click();
    await expect(page.locator("#deck-preview-title")).toHaveText("Mountain");
    await expect(page.locator(".deck-preview-dialog")).toContainText("Need 1 · Have 0 · Missing 1");
    await expect(page.locator(".deck-preview-art img")).toHaveJSProperty("complete", true);
    expect(await page.locator(".deck-preview-art img").evaluate((image) => (image as HTMLImageElement).naturalWidth)).toBeGreaterThan(0);
    await page.screenshot({ path: `../../artifacts/deck-collection/live-preview-${browser.browserType().name()}.png`, fullPage: true });
    await page.getByRole("button", { name: "Close deck card preview", exact: true }).click();
    await page.setViewportSize({ width: 320, height: 844 });
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
    expect(errors).toEqual([]);
    expect((await (await context.request.get("/api/v1/collection")).json()).copies).toBe(2);
  } finally { await context.close().catch(() => {}); await account.remove(); }
});
