import { expect, test } from "@playwright/test";
import { createCollector } from "./account";
import { navigate, skipWelcomeTour } from "./navigation";

test("text imports default to nonfoil and explain explicitly unknown finishes", async ({ browser, request }) => {
  const account = await createCollector(request);
  const candidates = (await (await request.get(account.baseURL + "/api/v1/catalog/search?q=Forest")).json()).items;
  const card = candidates.find((value: { name: string; language: string; finishes: string[] }) => value.name === "Forest" && value.language === "en" && value.finishes.includes("nonfoil") && value.finishes.includes("foil"));
  expect(card).toBeTruthy();
  const context = await browser.newContext({ baseURL: account.baseURL, viewport: { width: 390, height: 844 }, isMobile: true, hasTouch: true });
  try {
    const page = await context.newPage(); const errors: string[] = [];
    page.on("pageerror", (error) => errors.push(error.message));
    await page.goto("/");
    await page.getByRole("link", { name: "Sign in", exact: true }).click();
    await page.locator("#username").fill(account.username); await page.locator("#password").fill(account.password); await page.locator("#kc-login").click();
    await skipWelcomeTour(page);
    await navigate(page, "Import / export");
    const line = `${card.name} (${card.set_code.toUpperCase()}) ${card.collector_number}`;
    await page.getByTestId("csv-input").setInputFiles({ name: "known-text-finishes.txt", mimeType: "text/plain", buffer: Buffer.from(`3 ${line}\n2 ${line} *F*\n`) });
    await expect(page.getByRole("heading", { name: "Ready to review", exact: true })).toBeVisible({ timeout: 30000 });
    await expect(page.getByText(/^Unmarked entries: normal \/ nonfoil/)).toBeVisible();
    await page.getByLabel("These are cards I own. Add the reviewed quantities to my collection.").check();
    await page.getByRole("button", { name: "Add 5 copies", exact: true }).click();
    await expect(page.getByRole("heading", { name: "Import complete", exact: true })).toBeVisible({ timeout: 30000 });
    const lots = (await (await context.request.get("/api/v1/collection")).json()).items;
    expect(lots.map((lot: { finish: string; quantity: number }) => [lot.finish, lot.quantity]).sort()).toEqual([["foil", 2], ["nonfoil", 3]]);
    await page.getByTestId("csv-input").setInputFiles({ name: "uncertain-text-finishes.txt", mimeType: "text/plain", buffer: Buffer.from(`4 ${line}\n`) });
    await expect(page.getByRole("heading", { name: "Ready to review", exact: true })).toBeVisible({ timeout: 30000 });
    await page.getByText("Column mapping and file options", { exact: true }).click();
    await page.getByRole("combobox", { name: "Unmarked text entries", exact: true }).selectOption("unknown");
    await page.getByRole("button", { name: "Rebuild preview", exact: true }).click();
    await expect(page.getByText(/^Unmarked entries: unknown finish/)).toBeVisible({ timeout: 30000 });
    await expect(page.getByRole("heading", { name: "Ready to review", exact: true })).toBeVisible({ timeout: 30000 });
    await page.getByLabel("These are cards I own. Add the reviewed quantities to my collection.").check();
    await page.getByRole("button", { name: "Add 4 copies", exact: true }).click();
    await expect(page.getByRole("heading", { name: "Import complete", exact: true })).toBeVisible({ timeout: 30000 });
    await navigate(page, "Collection");
    await expect(page.getByText("9 copies", { exact: true })).toBeVisible();
    await page.getByText("Why are some copies unpriced?", { exact: true }).click();
    await expect(page.locator(".pricing-help")).toContainText("4 copies have no recorded finish");
    const valuation = (await (await context.request.get("/api/v1/collection/cards")).json()).valuation;
    expect(valuation.pricing_issues.unknown_finish).toBe(4);
    expect(valuation.priced_copies).toBe(5);
    await page.getByRole("button", { name: "Show copies needing a finish" }).click();
    await expect(page.locator(".gallery-card-price")).toContainText("Finish not set");
    await expect(page.getByText("4 copies", { exact: true })).toBeVisible();
    await page.locator(".gallery-card").click();
    const dialog = page.getByRole("dialog");
    await dialog.getByText("Manage copies", { exact: true }).click();
    const unknown = dialog.locator(".copy-groups > li").filter({ hasText: "Unknown finish" });
    await unknown.getByText("Edit card details", { exact: true }).click();
    await unknown.getByRole("combobox", { name: "Card finish", exact: true }).selectOption("nonfoil");
    await unknown.getByRole("button", { name: "Save card details", exact: true }).click();
    await expect(dialog).toHaveCount(0);
    await page.getByRole("button", { name: "Clear search & filters", exact: true }).click();
    await expect(page.getByText("9 copies", { exact: true })).toBeVisible();
    const corrected = (await (await context.request.get("/api/v1/collection/cards")).json()).valuation;
    expect(corrected.priced_copies).toBe(9);
    expect(corrected.unpriced_copies).toBe(0);
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
    expect(errors).toEqual([]);
  } finally { await context.close().catch(() => {}); await account.remove(); }
});
