"""local catalog card regions and collection transfers"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "756dc6210905"
down_revision = "d04621c0e623"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "catalog_snapshots",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("source", sa.String(length=512), nullable=False),
        sa.Column("checksum", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("printings", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("checksum"),
    )
    op.create_table(
        "binders",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("owner_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id", "owner_id"),
        sa.UniqueConstraint("owner_id", "name"),
    )
    op.create_table(
        "card_printings",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("oracle_id", sa.Uuid(), nullable=True),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("set_code", sa.String(length=16), nullable=False),
        sa.Column("collector_number", sa.String(length=32), nullable=False),
        sa.Column("language", sa.String(length=16), nullable=False),
        sa.Column("finishes", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("source_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("snapshot_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["snapshot_id"],
            ["catalog_snapshots.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_card_printings_name"), "card_printings", ["name"], unique=False)
    op.create_index(
        op.f("ix_card_printings_oracle_id"), "card_printings", ["oracle_id"], unique=False
    )
    op.create_index(
        "printing_identifiers",
        "card_printings",
        ["set_code", "collector_number", "language"],
        unique=False,
    )
    op.create_table(
        "imports",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("owner_id", sa.UUID(), nullable=False),
        sa.Column("request_key", sa.String(length=128), nullable=False),
        sa.Column("request_hash", sa.String(length=64), nullable=False),
        sa.Column("filename", sa.String(length=255), nullable=False),
        sa.Column("checksum", sa.String(length=64), nullable=False),
        sa.Column("source_key", sa.String(length=512), nullable=True),
        sa.Column("format", sa.String(length=32), nullable=False),
        sa.Column("adapter_version", sa.String(length=32), nullable=False),
        sa.Column("mapping", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("options", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("headers", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("state", sa.String(length=32), nullable=False),
        sa.Column("summary", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("error", sa.String(length=512), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("owner_id", "request_key"),
    )
    op.create_index("import_owner_checksum", "imports", ["owner_id", "checksum"], unique=False)
    op.create_table(
        "exports",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("owner_id", sa.UUID(), nullable=False),
        sa.Column("request_key", sa.String(length=128), nullable=False),
        sa.Column("request_hash", sa.String(length=64), nullable=False),
        sa.Column("format", sa.String(length=32), nullable=False),
        sa.Column("binder_id", sa.Uuid(), nullable=True),
        sa.Column("state", sa.String(length=32), nullable=False),
        sa.Column("snapshot_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("object_key", sa.String(length=512), nullable=True),
        sa.Column("checksum", sa.String(length=64), nullable=True),
        sa.Column("report", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("losses_acknowledged", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["binder_id"],
            ["binders.id"],
        ),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("owner_id", "request_key"),
    )
    op.create_table(
        "import_rows",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("import_id", sa.Uuid(), nullable=False),
        sa.Column("row_number", sa.Integer(), nullable=False),
        sa.Column("raw_fields", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("normalized", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("printing_id", sa.Uuid(), nullable=True),
        sa.Column("quantity", sa.Integer(), nullable=True),
        sa.Column("state", sa.String(length=32), nullable=False),
        sa.Column("error", sa.String(length=512), nullable=True),
        sa.ForeignKeyConstraint(["import_id"], ["imports.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["printing_id"],
            ["card_printings.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("import_id", "row_number"),
    )
    op.create_table(
        "observations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("scan_id", sa.UUID(), nullable=False),
        sa.Column("region_index", sa.Integer(), nullable=False),
        sa.Column("polygon", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("crop_key", sa.String(length=512), nullable=True),
        sa.Column("detector_version", sa.String(length=64), nullable=False),
        sa.Column("state", sa.String(length=32), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["scan_id"], ["scans.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("scan_id", "region_index"),
    )
    op.create_table(
        "export_rows",
        sa.Column("export_id", sa.Uuid(), nullable=False),
        sa.Column("lot_id", sa.Uuid(), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(["export_id"], ["exports.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("export_id", "lot_id"),
    )
    op.create_table(
        "inventory_lots",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("owner_id", sa.UUID(), nullable=False),
        sa.Column("binder_id", sa.Uuid(), nullable=False),
        sa.Column("printing_id", sa.Uuid(), nullable=False),
        sa.Column("quantity_remaining", sa.Integer(), nullable=False),
        sa.Column("finish", sa.String(length=32), nullable=False),
        sa.Column("condition", sa.String(length=32), nullable=False),
        sa.Column("notes", sa.String(length=4096), nullable=False),
        sa.Column("purchase_price", sa.Numeric(precision=16, scale=4), nullable=True),
        sa.Column("purchase_currency", sa.String(length=3), nullable=True),
        sa.Column("misprint", sa.Boolean(), nullable=True),
        sa.Column("altered", sa.Boolean(), nullable=True),
        sa.Column("source_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("source_import_row_id", sa.Uuid(), nullable=True),
        sa.Column("source_observation_id", sa.Uuid(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "condition IN ('ungraded','NM','LP','MP','HP','damaged')", name="lot_valid_condition"
        ),
        sa.CheckConstraint(
            "finish IN ('unknown','nonfoil','foil','etched')", name="lot_valid_finish"
        ),
        sa.CheckConstraint(
            "num_nonnulls(source_import_row_id, source_observation_id) <= 1", name="lot_one_source"
        ),
        sa.CheckConstraint("quantity_remaining >= 0", name="lot_nonnegative_quantity"),
        sa.ForeignKeyConstraint(
            ["binder_id", "owner_id"],
            ["binders.id", "binders.owner_id"],
        ),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["printing_id"],
            ["card_printings.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_import_row_id"],
            ["import_rows.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_observation_id"],
            ["observations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source_import_row_id"),
        sa.UniqueConstraint("source_observation_id"),
    )
    op.create_index(
        op.f("ix_inventory_lots_owner_id"), "inventory_lots", ["owner_id"], unique=False
    )
    op.create_table(
        "inventory_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("lot_id", sa.Uuid(), nullable=False),
        sa.Column("operation_key", sa.String(length=128), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("delta", sa.Integer(), nullable=False),
        sa.Column("detail", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["lot_id"], ["inventory_lots.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("operation_key"),
    )
    op.create_index(
        op.f("ix_inventory_events_lot_id"), "inventory_events", ["lot_id"], unique=False
    )
    op.add_column("jobs", sa.Column("import_id", sa.Uuid(), nullable=True))
    op.add_column("jobs", sa.Column("export_id", sa.Uuid(), nullable=True))
    op.alter_column("jobs", "scan_id", existing_type=sa.UUID(), nullable=True)
    op.create_unique_constraint("jobs_import_id_kind_key", "jobs", ["import_id", "kind"])
    op.create_unique_constraint("jobs_export_id_key", "jobs", ["export_id"])
    op.create_foreign_key(
        "jobs_import_id_fkey", "jobs", "imports", ["import_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        "jobs_export_id_fkey", "jobs", "exports", ["export_id"], ["id"], ondelete="CASCADE"
    )
    op.create_check_constraint(
        "job_one_resource", "jobs", "num_nonnulls(scan_id, import_id, export_id) = 1"
    )
    op.create_check_constraint(
        "job_kind_resource",
        "jobs",
        "(kind = 'PREPARE_IMAGE' AND scan_id IS NOT NULL) OR (kind IN ('IMPORT_PREVIEW','IMPORT_COMMIT','IMPORT_UNDO') AND import_id IS NOT NULL) OR (kind = 'EXPORT' AND export_id IS NOT NULL)",
    )
    # ### end Alembic commands ###


def downgrade():
    # Old workers assume every job is a scan; restoring only old code is unsafe.
    raise RuntimeError(
        "Restore the coordinated pre-upgrade backup to roll back collection transfers."
    )
